apiVersion: v1
kind: Namespace
metadata:
  labels:
    cluster: cluster-west
    owner: platform-team
    istio.io/rev: asm-195-2
  name: gamestore
---
apiVersion: v1
kind: ResourceQuota
metadata:
  labels:
    owner: platform-team
  name: hard-limit
  namespace: gamestore
spec:
  hard:
    cpu: "20"
    memory: 2Gi
    pods: "50"