apiVersion: v1
kind: Namespace
metadata:
  labels:
    cluster: cluster-east
    owner: platform-team
  name: gamestore
---
apiVersion: v1
kind: ResourceQuota
metadata:
  labels:
    owner: platform-team
  name: hard-limit
  namespace: gamestore
spec:
  hard:
    cpu: "10"
    memory: 2Gi
    pods: "50"